---
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./satellite/

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

nfpms:
  - id: satellite
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/t94j0/satellite
    maintainer: Max Harley <maxh@maxh.io>
    description: easy-to-use payload hosting
    license: MIT
    dependencies:
      - openssl
    scripts:
      postinstall: ".config/scripts/postinstall.sh"
    formats:
      - deb
      - rpm
    empty_folders:
      - /var/www/html
    contents:
      - src: ".config/etc/satellite/config.yml"
        dst: "/etc/satellite/config.yml"
        type: config

      - src: ".config/lib/systemd/system/satellite.service"
        dst: "/lib/systemd/system/satellite.service"
        type: config

      - src: ".config/var/lib/satellite/GeoLite2-Country.mmdb"
        dst: "/var/lib/satellite/GeoLite2-Country.mmdb"
        type: config

brews:
  - name: satellite
    skip_upload: true
    tap:
      owner: t94j0
      name: homebrew-security
    url_template: "https://github.com/t94j0/satellite/releases/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Max Harley
      email: maxh@maxh.io
    folder: Formula
    homepage: "https://github.com/t94j0/satellite"
    description: "easy-to-use payload hosting"
    install: |
      bin.install "satellite"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
